package cpu

var OpCodes = [256]OpCode{
	OpCode{"BRK", 7, false, Implied, BRK},
	OpCode{"ORA", 6, false, IndirectX, ORA},
	OpCode{},
	OpCode{},
	OpCode{},
	OpCode{"ORA", 3, false, ZeroPage, ORA},
	OpCode{"ASL", 5, false, ZeroPage, ASL},
	OpCode{},

	OpCode{"PHP", 3, false, Implied, PHP},
	OpCode{"ORA", 2, false, Immediate, ORA},
	OpCode{"ASL", 2, false, Accumulator, ASL},
	OpCode{},
	OpCode{},
	OpCode{"ORA", 4, false, Absolute, ORA},
	OpCode{"ASL", 6, false, Absolute, ASL},
	OpCode{},

	OpCode{"BPL", 2, true, Relative, BPL},
	OpCode{"ORA", 5, true, IndirectY, ORA},
	OpCode{},
	OpCode{},
	OpCode{},
	OpCode{"ORA", 4, false, ZeroPageX, ORA},
	OpCode{"ASL", 6, false, ZeroPageX, ASL},
	OpCode{},

	OpCode{"CLC", 2, false, Implied, CLC},
	OpCode{"ORA", 4, true, AbsoluteY, ORA},
	OpCode{},
	OpCode{},
	OpCode{},
	OpCode{"ORA", 4, true, AbsoluteX, ORA},
	OpCode{"ASL", 7, false, AbsoluteX, ASL},
	OpCode{},

	OpCode{"JSR", 6, false, Absolute, JSR},
	OpCode{"AND", 6, false, IndirectX, AND},
	OpCode{},
	OpCode{},
	OpCode{"BIT", 3, false, ZeroPage, BIT},
	OpCode{"AND", 3, false, ZeroPage, AND},
	OpCode{"ROL", 5, false, ZeroPage, ROL},
	OpCode{},

	OpCode{"PLP", 4, false, Implied, PLP},
	OpCode{"AND", 2, false, Immediate, AND},
	OpCode{"ROL", 2, false, Accumulator, ROL},
	OpCode{},
	OpCode{"BIT", 4, false, Absolute, BIT},
	OpCode{"AND", 4, false, Absolute, AND},
	OpCode{"ROL", 6, false, Absolute, ROL},
	OpCode{},

	OpCode{"BMI", 2, true, Relative, BMI},
	OpCode{"AND", 5, true, IndirectY, AND},
	OpCode{},
	OpCode{},
	OpCode{},
	OpCode{"AND", 4, false, ZeroPageX, AND},
	OpCode{"ROL", 6, false, ZeroPageX, ROL},
	OpCode{},

	OpCode{"SEC", 2, false, Implied, SEC},
	OpCode{"AND", 4, true, AbsoluteY, AND},
	OpCode{},
	OpCode{},
	OpCode{},
	OpCode{"AND", 4, true, AbsoluteX, AND},
	OpCode{"ROL", 7, false, AbsoluteX, ROL},
	OpCode{},

	OpCode{"RTI", 6, false, Implied, RTI},
	OpCode{"EOR", 6, false, IndirectX, EOR},
	OpCode{},
	OpCode{},
	OpCode{},
	OpCode{"EOR", 3, false, ZeroPage, EOR},
	OpCode{"LSR", 5, false, ZeroPage, LSR},
	OpCode{},

	OpCode{"PHA", 3, false, Implied, PHA},
	OpCode{"EOR", 2, false, Immediate, EOR},
	OpCode{"LSR", 2, false, Accumulator, LSR},
	OpCode{},
	OpCode{"JMP", 3, false, Absolute, JMP},
	OpCode{"EOR", 4, false, Absolute, EOR},
	OpCode{"LSR", 6, false, Absolute, LSR},
	OpCode{},

	OpCode{"BVC", 2, true, Relative, BVC},
	OpCode{"EOR", 5, true, IndirectY, EOR},
	OpCode{},
	OpCode{},
	OpCode{},
	OpCode{"EOR", 4, false, ZeroPageX, EOR},
	OpCode{"LSR", 6, false, ZeroPageX, LSR},
	OpCode{},

	OpCode{"CLI", 2, false, Implied, CLI},
	OpCode{"EOR", 4, true, AbsoluteY, EOR},
	OpCode{},
	OpCode{},
	OpCode{},
	OpCode{"EOR", 4, true, AbsoluteX, EOR},
	OpCode{"LSR", 7, false, AbsoluteX, LSR},
	OpCode{},

	OpCode{"RTS", 6, false, Implied, RTS},
	OpCode{"ADC", 6, false, IndirectX, ADC},
	OpCode{},
	OpCode{},
	OpCode{},
	OpCode{"ADC", 3, false, ZeroPage, ADC},
	OpCode{"ROR", 5, false, ZeroPage, ROR},
	OpCode{},

	OpCode{"PLA", 4, false, Implied, PLA},
	OpCode{"ADC", 2, false, Immediate, ADC},
	OpCode{"ROR", 2, false, Accumulator, ROR},
	OpCode{},
	OpCode{"JMP", 5, false, Indirect, JMP},
	OpCode{"ADC", 4, false, Absolute, ADC},
	OpCode{"ROR", 6, false, Absolute, ROR},
	OpCode{},

	OpCode{"BVS", 2, true, Relative, BVS},
	OpCode{"ADC", 5, true, IndirectY, ADC},
	OpCode{},
	OpCode{},
	OpCode{},
	OpCode{"ADC", 4, false, ZeroPageX, ADC},
	OpCode{"ROR", 6, false, ZeroPageX, ROR},
	OpCode{},

	OpCode{"SEI", 2, false, Implied, SEI},
	OpCode{"ADC", 4, true, AbsoluteY, ADC},
	OpCode{},
	OpCode{},
	OpCode{},
	OpCode{"ADC", 4, true, AbsoluteX, ADC},
	OpCode{"ROR", 7, false, AbsoluteX, ROR},
	OpCode{},

	OpCode{},
	OpCode{"STA", 6, false, IndirectX, STA},
	OpCode{},
	OpCode{},
	OpCode{"STY", 3, false, ZeroPage, STY},
	OpCode{"STA", 3, false, ZeroPage, STA},
	OpCode{"STX", 3, false, ZeroPage, STX},
	OpCode{},

	OpCode{"DEY", 2, false, Implied, DEY},
	OpCode{},
	OpCode{"TXA", 2, false, Implied, TXA},
	OpCode{},
	OpCode{"STY", 4, false, Absolute, STY},
	OpCode{"STA", 4, false, Absolute, STA},
	OpCode{"STX", 4, false, Absolute, STX},
	OpCode{},

	OpCode{"BCC", 2, true, Relative, BCC},
	OpCode{"STA", 6, false, IndirectY, STA},
	OpCode{},
	OpCode{},
	OpCode{"STY", 4, false, ZeroPageX, STY},
	OpCode{"STA", 4, false, ZeroPageX, STA},
	OpCode{"STX", 4, false, ZeroPageY, STX},
	OpCode{},

	OpCode{"TYA", 2, false, Implied, TYA},
	OpCode{"STA", 5, false, AbsoluteY, STA},
	OpCode{"TXS", 2, false, Implied, TXS},
	OpCode{},
	OpCode{},
	OpCode{"STA", 5, true, AbsoluteX, STA},
	OpCode{},
	OpCode{},

	OpCode{"LDY", 2, false, Immediate, LDY},
	OpCode{"LDA", 6, false, IndirectX, LDA},
	OpCode{"LDX", 2, false, Immediate, LDX},
	OpCode{},
	OpCode{"LDY", 3, false, ZeroPage, LDY},
	OpCode{"LDA", 3, false, ZeroPage, LDA},
	OpCode{"LDX", 3, false, ZeroPage, LDX},
	OpCode{},

	OpCode{"TAY", 2, false, Implied, TAY},
	OpCode{"LDA", 2, false, Immediate, LDA},
	OpCode{"TAX", 2, false, Implied, TAX},
	OpCode{},
	OpCode{"LDY", 4, false, Absolute, LDY},
	OpCode{"LDA", 4, false, Absolute, LDA},
	OpCode{"LDX", 4, false, Absolute, LDX},
	OpCode{},

	OpCode{"BCS", 2, true, Relative, BCS},
	OpCode{"LDA", 5, true, IndirectY, LDA},
	OpCode{},
	OpCode{},
	OpCode{"LDY", 4, false, ZeroPageX, LDY},
	OpCode{"LDA", 4, false, ZeroPageX, LDA},
	OpCode{"LDX", 4, false, ZeroPageY, LDX},
	OpCode{},

	OpCode{"CLV", 2, false, Implied, CLV},
	OpCode{"LDA", 4, true, AbsoluteY, LDA},
	OpCode{"TSX", 2, false, Implied, TSX},
	OpCode{},
	OpCode{"LDY", 4, true, AbsoluteX, LDY},
	OpCode{"LDA", 4, true, AbsoluteX, LDA},
	OpCode{"LDX", 4, true, AbsoluteY, LDX},
	OpCode{},

	OpCode{"CPY", 2, false, Immediate, CPY},
	OpCode{"CMP", 6, false, IndirectX, CMP},
	OpCode{},
	OpCode{},
	OpCode{"CPY", 3, false, ZeroPage, CPY},
	OpCode{"CMP", 3, false, ZeroPage, CMP},
	OpCode{"DEC", 5, false, ZeroPage, DEC},
	OpCode{},

	OpCode{"INY", 2, false, Implied, INY},
	OpCode{"CMP", 2, false, Immediate, CMP},
	OpCode{"DEX", 2, false, Implied, DEX},
	OpCode{},
	OpCode{"CPY", 4, false, Absolute, CPY},
	OpCode{"CMP", 4, false, Absolute, CMP},
	OpCode{"DEC", 6, false, Absolute, DEC},
	OpCode{},

	OpCode{"BNE", 2, true, Relative, BNE},
	OpCode{"CMP", 5, true, IndirectY, CMP},
	OpCode{},
	OpCode{},
	OpCode{},
	OpCode{"CMP", 4, false, ZeroPageX, CMP},
	OpCode{"DEC", 6, false, ZeroPageX, DEC},
	OpCode{},

	OpCode{"CLD", 2, false, Implied, CLD},
	OpCode{"CMP", 4, true, AbsoluteY, CMP},
	OpCode{},
	OpCode{},
	OpCode{},
	OpCode{"CMP", 4, true, AbsoluteX, CMP},
	OpCode{"DEC", 7, false, AbsoluteX, DEC},
	OpCode{},

	OpCode{"CPX", 2, false, Immediate, CPX},
	OpCode{"SBC", 6, false, IndirectX, SBC},
	OpCode{},
	OpCode{},
	OpCode{"CPX", 3, false, ZeroPage, CPX},
	OpCode{"SBC", 3, false, ZeroPage, SBC},
	OpCode{"INC", 5, false, ZeroPage, INC},
	OpCode{},

	OpCode{"INX", 2, false, Implied, INX},
	OpCode{"SBC", 2, false, Immediate, SBC},
	OpCode{"NOP", 2, false, Implied, NOP},
	OpCode{},
	OpCode{"CPX", 4, false, Absolute, CPX},
	OpCode{"SBC", 4, false, Absolute, SBC},
	OpCode{"INC", 6, false, Absolute, INC},
	OpCode{},

	OpCode{"BEQ", 2, true, Relative, BEQ},
	OpCode{"SBC", 5, true, IndirectY, SBC},
	OpCode{},
	OpCode{},
	OpCode{},
	OpCode{"SBC", 4, false, ZeroPageX, SBC},
	OpCode{"INC", 6, false, ZeroPageX, INC},
	OpCode{},

	OpCode{"SED", 2, false, Implied, SED},
	OpCode{"SBC", 4, true, AbsoluteY, SBC},
	OpCode{},
	OpCode{},
	OpCode{},
	OpCode{"SBC", 4, true, AbsoluteX, SBC},
	OpCode{"INC", 7, false, AbsoluteX, INC},
	OpCode{},
}
